# Generated by Django 3.2.17 on 2023-04-02 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='members',
        ),
        migrations.RemoveField(
            model_name='room',
            name='turn_player',
        ),
    ]
