# Generated by Django 3.2.17 on 2023-04-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20230403_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='previous_artist',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='current_artist',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
