# Generated by Django 3.2.17 on 2023-04-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20230406_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
